GET http://localhost:1323/cars

###

GET http://localhost:1323/cars/0

###

POST http://localhost:1323/cars
Content-Type: application/json

{
    "name": "Toyota Altis",
    "price": 75000,
    "discount": 12
}

###

PATCH http://localhost:1323/cars/1
Content-Type: application/json

{
  "price": 7000
}

###
PATCH http://localhost:1323/cars/1
Content-Type: application/json

{
  "discount": 15
}

###

DELETE http://localhost:1323/cars/1
